#!/bin/sh
mkdir -p target
#codium .
make
#okular target/main.pdf &

inotifywait -e modify -r -m src |
    while read path action file; do
        (  \
            cd src; \
            pdflatex -output-directory="../target" main.tex; \
    	);
    done
